name: OWASP Dependency Check

on:
  push:
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Run OWASP Dependency Check
        run: |
          mvn org.owasp:dependency-check-maven:check \
          -DfailBuildOnCVSS=11 \
          -DnodeAuditAnalyzerEnabled=false \
          -DpnpmAuditAnalyzerEnabled=false \
          -DyarnAuditAnalyzerEnabled=false \
          -DnpmAuditAnalyzerEnabled=false \
          -DretireJsAnalyzerEnabled=false

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: '**/dependency-check-report.html'
          if-no-files-found: warn
